import type { Metadata } from "next";
import React from "react";
import { Inter } from "next/font/google";

import "@/styles/globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { CartProvider } from "@/context/CartContext";
import Footer from "@/components/Footer";
import { StickyNavbar } from "@/components/Navbar";
import FooterConditional from "@/components/Footer/footerConditional";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <CartProvider>
            <div className="  fixed inset-x-0 top-0 z-20 ">
              <StickyNavbar />
            </div>

            <div>{children}</div>
            <FooterConditional>
              <Footer />
            </FooterConditional>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
